// questions.js - Database completo con focus sul conflitto israelo-palestinese
// Ogni categoria ha 60+ domande (20+ per difficoltà)

const QUESTIONS = [
  // ==================== STORIA ====================
  // EASY (30)
  { q: "Quali due popoli sono coinvolti nel conflitto israelo-palestinese?", choices: ["Israeliani e palestinesi", "Spagnoli e portoghesi", "Greci e turchi"], a: 0, difficulty: "easy", category: "storia", explanation: "Il conflitto israelo-palestinese coinvolge israeliani (prevalentemente ebrei) e palestinesi (prevalentemente arabi musulmani e cristiani). È uno dei conflitti più lunghi e complessi della storia moderna.", sources: [{title: "Storia del conflitto - Enciclopedia Treccani", url: "https://www.treccani.it/enciclopedia/conflitto-arabo-israeliano"}, {title: "Documentario RAI Storia", url: "https://www.raiplay.it/programmi/israelianipalestinesi"}] },
  { q: "Qual è la città sacra per tre religioni?", choices: ["Il Cairo", "Gerusalemme", "Riyad"], a: 1, difficulty: "easy", category: "storia", explanation: "Gerusalemme è sacra per ebraismo, cristianesimo e islam. Per gli ebrei ospita il Muro del Pianto, per i cristiani i luoghi della passione di Cristo, per i musulmani la Cupola della Roccia e la moschea di Al-Aqsa.", sources: [{title: "Gerusalemme città sacra - Focus", url: "https://www.focus.it/cultura/storia/gerusalemme-citta-sacra"}, {title: "UNESCO World Heritage", url: "https://whc.unesco.org/en/list/148/"}] },
  { q: "Come si chiama la Striscia governata da Hamas?", choices: ["Sinai", "Striscia di Gaza", "Cisgiordania"], a: 1, difficulty: "easy", category: "storia", explanation: "La Striscia di Gaza è un territorio palestinese di 365 km² controllato da Hamas dal 2007. È una delle aree più densamente popolate al mondo con circa 2 milioni di abitanti.", sources: [{title: "Striscia di Gaza - BBC", url: "https://www.bbc.com/news/world-middle-east"}, {title: "UNRWA Gaza", url: "https://www.unrwa.org/where-we-work/gaza-strip"}] },
  { q: "Quale Stato fu fondato nel 1948?", choices: ["Libano", "Giordania", "Israele"], a: 2, difficulty: "easy", category: "storia", explanation: "Israele fu proclamato il 14 maggio 1948 da David Ben-Gurion. Questo evento scatenò la prima guerra arabo-israeliana e l'esodo di centinaia di migliaia di palestinesi.", sources: [{title: "Dichiarazione indipendenza Israele", url: "https://www.mfa.gov.il/mfa/foreignpolicy/peace/guide/pages/declaration%20of%20establishment%20of%20state%20of%20israel.aspx"}, {title: "1948: la Nakba palestinese", url: "https://www.aljazeera.com/features/2017/5/23/the-nakba-did-not-start-or-end-in-1948"}] },
  { q: "Quale organizzazione rappresenta i palestinesi?", choices: ["OLP", "ONU", "NATO"], a: 0, difficulty: "easy", category: "storia", explanation: "L'OLP (Organizzazione per la Liberazione della Palestina) fu fondata nel 1964 e guidata da Yasser Arafat dal 1969. Nel 1993 firmò gli Accordi di Oslo con Israele.", sources: [{title: "Storia dell'OLP", url: "https://www.britannica.com/topic/Palestine-Liberation-Organization"}, {title: "Accordi di Oslo", url: "https://peacemaker.un.org/israelopt-osloaccord93"}] },
  { q: "Quale mare è a ovest di Israele?", choices: ["Mar Nero", "Mar Rosso", "Mar Mediterraneo"], a: 2, difficulty: "easy", category: "storia" },
  { q: "Quale ente propone risoluzioni sul conflitto?", choices: ["UEFA", "OMS", "ONU"], a: 2, difficulty: "easy", category: "storia" },
  { q: "Quali territori formerebbero lo Stato palestinese?", choices: ["Cisgiordania e Gaza", "Egitto e Giordania", "Libano e Siria"], a: 0, difficulty: "easy", category: "storia", explanation: "Lo Stato palestinese dovrebbe comprendere la Cisgiordania (West Bank) e la Striscia di Gaza, territori occupati da Israele nel 1967. La 'soluzione dei due Stati' prevede Israele e Palestina come stati indipendenti affiancati.", sources: [{title: "Two-State Solution - UN", url: "https://www.un.org/unispal/data-collection/two-state-solution/"}, {title: "Territori palestinesi - Britannica", url: "https://www.britannica.com/place/Palestinian-territories"}] },
  { q: "In che anno cadde il Muro di Berlino?", choices: ["1987", "1989", "1991"], a: 1, difficulty: "easy", category: "storia" },
  { q: "Chi fu il primo presidente USA?", choices: ["Abraham Lincoln", "Thomas Jefferson", "George Washington"], a: 2, difficulty: "easy", category: "storia" },
  { q: "Quando iniziò la Seconda Guerra Mondiale?", choices: ["1939", "1941", "1937"], a: 0, difficulty: "easy", category: "storia" },
  { q: "Chi guidò i diritti civili negli USA?", choices: ["Malcolm X", "Martin Luther King Jr.", "Rosa Parks"], a: 1, difficulty: "easy", category: "storia" },
  { q: "Quando Colombo scoprì l'America?", choices: ["1500", "1492", "1520"], a: 1, difficulty: "easy", category: "storia" },
  { q: "Chi fu il primo imperatore romano?", choices: ["Augusto", "Cesare", "Nerone"], a: 0, difficulty: "easy", category: "storia" },
  { q: "Quando finì la Prima Guerra Mondiale?", choices: ["1920", "1918", "1914"], a: 1, difficulty: "easy", category: "storia" },
  { q: "Quale religione nacque in Palestina?", choices: ["Buddismo", "Cristianesimo", "Islam"], a: 1, difficulty: "easy", category: "storia", explanation: "Il Cristianesimo nacque in Palestina nel I secolo d.C. con la predicazione di Gesù Cristo. La regione è quindi sacra non solo per ebrei e musulmani, ma anche per i cristiani di tutto il mondo.", sources: [{title: "Origini del Cristianesimo", url: "https://www.treccani.it/enciclopedia/cristianesimo"}, {title: "Terra Santa cristiana", url: "https://www.vatican.va/roman_curia/congregations/corient/documents/rc_con_corient_doc_20060526_terra-santa_it.html"}] },
  { q: "Quale città è capitale de facto di Israele?", choices: ["Haifa", "Gerusalemme", "Tel Aviv"], a: 1, difficulty: "easy", category: "storia", explanation: "Gerusalemme è la capitale dichiarata da Israele, ma non è riconosciuta dalla maggioranza della comunità internazionale. Molti paesi mantengono le loro ambasciate a Tel Aviv.", sources: [{title: "Status di Gerusalemme - BBC", url: "https://www.bbc.com/news/world-middle-east-44124556"}, {title: "Questione Gerusalemme capitale", url: "https://www.ispionline.it/it/pubblicazione/gerusalemme-capitale-israele-23419"}] },
  { q: "Chi fu Napoleone Bonaparte?", choices: ["Re inglese", "Imperatore francese", "Zar russo"], a: 1, difficulty: "easy", category: "storia" },
  { q: "Quale paese confinava con Palestina a sud?", choices: ["Arabia Saudita", "Iraq", "Egitto"], a: 2, difficulty: "easy", category: "storia" },
  { q: "In che secolo visse Leonardo da Vinci?", choices: ["XIII-XIV", "XV-XVI", "XVII-XVIII"], a: 1, difficulty: "easy", category: "storia" },
  { q: "Quale movimento fondò Israele?", choices: ["Sionismo", "Socialismo", "Liberalismo"], a: 0, difficulty: "easy", category: "storia", explanation: "Il Sionismo è il movimento politico che sostiene il diritto del popolo ebraico ad avere un proprio Stato in Israele. Fu fondato da Theodor Herzl nel 1897 e portò alla creazione di Israele nel 1948.", sources: [{title: "Storia del Sionismo", url: "https://www.britannica.com/topic/Zionism"}, {title: "Theodor Herzl", url: "https://www.jewishvirtuallibrary.org/theodor-herzl"}] },
  { q: "Chi fu Giulio Cesare?", choices: ["Filosofo greco", "Generale romano", "Imperatore bizantino"], a: 1, difficulty: "easy", category: "storia" },
  { q: "Chi controllò la Palestina dal 1920-1948?", choices: ["Francia", "Italia", "Gran Bretagna"], a: 2, difficulty: "easy", category: "storia", explanation: "La Gran Bretagna controllò la Palestina tramite un Mandato della Società delle Nazioni dal 1920 al 1948, dopo la caduta dell'Impero Ottomano. Il mandato includeva la promessa della Dichiarazione Balfour per un focolare ebraico.", sources: [{title: "Mandato britannico Palestina", url: "https://www.britannica.com/place/Palestine/British-mandate"}, {title: "Storia del Mandato - Treccani", url: "https://www.treccani.it/enciclopedia/mandato-britannico-sulla-palestina"}] },
  { q: "Quando cadde l'Impero Romano d'Occidente?", choices: ["400 d.C.", "500 d.C.", "476 d.C."], a: 2, difficulty: "easy", category: "storia" },
  { q: "Quale città è 'eterna' per Israele?", choices: ["Gerusalemme", "Haifa", "Tel Aviv"], a: 0, difficulty: "easy", category: "storia" },
  { q: "Chi scoprì la penicillina?", choices: ["Pasteur", "Koch", "Fleming"], a: 2, difficulty: "easy", category: "storia" },
  { q: "Quale conflitto fu chiamato 'Grande Guerra'?", choices: ["Guerra di Crimea", "Prima Guerra Mondiale", "Seconda Guerra Mondiale"], a: 1, difficulty: "easy", category: "storia" },
  { q: "Chi dipinse la Cappella Sistina?", choices: ["Raffaello", "Leonardo", "Michelangelo"], a: 2, difficulty: "easy", category: "storia" },
  { q: "Quale fiume bagna l'Egitto?", choices: ["Nilo", "Eufrate", "Tigri"], a: 0, difficulty: "easy", category: "storia" },
  { q: "In che anno l'uomo andò sulla Luna?", choices: ["1972", "1969", "1965"], a: 1, difficulty: "easy", category: "storia" },

  // NUOVE DOMANDE SUL CONFLITTO ISRAELO-PALESTINESE
  { q: "Quale muro divide Israele e Cisgiordania?", choices: ["Barriera di separazione", "Muro di Berlino", "Grande Muraglia"], a: 0, difficulty: "easy", category: "storia" },
  { q: "Quale città è contesa tra israeliani e palestinesi?", choices: ["Gerusalemme", "Parigi", "Roma"], a: 0, difficulty: "easy", category: "storia" },
  { q: "Quale lingua parlano i palestinesi?", choices: ["Ebraico", "Inglese", "Arabo"], a: 2, difficulty: "easy", category: "geografia" },
  { q: "Quale lingua parlano gli israeliani?", choices: ["Francese", "Ebraico", "Arabo"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Quale religione pratica la maggioranza palestinese?", choices: ["Islam", "Ebraismo", "Cristianesimo"], a: 0, difficulty: "easy", category: "storia" },
  { q: "Quale religione pratica la maggioranza israeliana?", choices: ["Islam", "Cristianesimo", "Ebraismo"], a: 2, difficulty: "easy", category: "storia" },
  { q: "Come si chiama l'altra zona palestinese oltre Gaza?", choices: ["Sinai", "Cisgiordania", "Golan"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Quale deserto si trova a sud di Israele?", choices: ["Gobi", "Sahara", "Negev"], a: 2, difficulty: "easy", category: "geografia" },
  { q: "Quale paese confina con Israele a nord?", choices: ["Turchia", "Libano", "Siria"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Quale organizzazione fu fondata da Arafat?", choices: ["Hamas", "Hezbollah", "Fatah"], a: 2, difficulty: "easy", category: "storia" },
  { q: "Quando iniziò la Prima Intifada?", choices: ["1967", "1987", "2000"], a: 1, difficulty: "medium", category: "storia", explanation: "La Prima Intifada ('sollevazione' in arabo) iniziò nel dicembre 1987 e durò fino al 1993. Fu una rivolta popolare palestinese contro l'occupazione israeliana, caratterizzata da proteste, scioperi e lancio di pietre.", sources: [{title: "Prima Intifada - Britannica", url: "https://www.britannica.com/event/intifada-Palestinian-uprising"}, {title: "Storia dell'Intifada", url: "https://www.aljazeera.com/features/2017/12/8/the-first-intifada-30-years-on"}] },
  { q: "Cosa significa 'Intifada' in arabo?", choices: ["Sollevazione", "Guerra", "Pace"], a: 0, difficulty: "medium", category: "storia" },
  { q: "Quale città palestinese è sede dell'Autorità Palestinese?", choices: ["Gaza", "Betlemme", "Ramallah"], a: 2, difficulty: "medium", category: "geografia" },
  { q: "In quale città nacque Gesù, oggi in Cisgiordania?", choices: ["Betlemme", "Nazaret", "Gerusalemme"], a: 0, difficulty: "medium", category: "storia" },
  { q: "Quale simbolo è sulla bandiera palestinese?", choices: ["Luna e stella", "Stella di David", "Nessun simbolo, solo colori"], a: 2, difficulty: "medium", category: "geografia" },
  { q: "Quale operazione militare israeliana colpì Gaza nel 2014?", choices: ["Protective Edge", "Piombo Fuso", "Pilastro di Difesa"], a: 0, difficulty: "medium", category: "storia" },
  { q: "Quanti rifugiati palestinesi ci sono oggi (circa)?", choices: ["5-6 milioni", "1-2 milioni", "10-12 milioni"], a: 0, difficulty: "medium", category: "storia" },
  { q: "Quale accordo portò pace tra Israele ed Egitto?", choices: ["Wye River", "Camp David", "Oslo"], a: 1, difficulty: "medium", category: "storia" },
  { q: "Chi fu il presidente USA che mediò Camp David 1978?", choices: ["Ronald Reagan", "Bill Clinton", "Jimmy Carter"], a: 2, difficulty: "medium", category: "storia" },
  { q: "Quale paese arabo non riconosce ancora Israele?", choices: ["Giordania", "Egitto", "Siria"], a: 2, difficulty: "medium", category: "storia" },
  { q: "Cosa stabiliva la Risoluzione ONU 242?", choices: ["Divisione Gerusalemme", "Ritiro territori occupati 1967", "Creazione Israele"], a: 1, difficulty: "hard", category: "storia", explanation: "La Risoluzione 242 del Consiglio di Sicurezza ONU (1967) chiede il ritiro delle forze israeliane dai territori occupati nella Guerra dei Sei Giorni e il riconoscimento del diritto di ogni Stato della regione a vivere in pace entro confini sicuri.", sources: [{title: "Testo Risoluzione 242", url: "https://www.un.org/unispal/document/auto-insert-179921/"}, {title: "Spiegazione Risoluzione 242", url: "https://www.britannica.com/topic/United-Nations-Resolution-242"}] },
  { q: "Quale fu l'esito della Conferenza di Madrid 1991?", choices: ["Fine conflitto", "Creazione ANP", "Avvio negoziati diretti"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Cosa sono gli insediamenti israeliani?", choices: ["Colonie in territori occupati", "Città israeliane", "Basi militari"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Quanti insediamenti ci sono in Cisgiordania (circa)?", choices: ["Oltre 130", "Circa 50", "Circa 20"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Cosa fu l'Operazione Pace in Galilea 1982?", choices: ["Guerra Sei Giorni", "Invasione Libano", "Ritiro da Gaza"], a: 1, difficulty: "hard", category: "storia" },
  { q: "Chi è considerato il padre del sionismo moderno?", choices: ["Chaim Weizmann", "Theodor Herzl", "David Ben-Gurion"], a: 1, difficulty: "hard", category: "storia" },
  { q: "Quando fu dichiarata l'indipendenza palestinese?", choices: ["1948", "1993", "1988"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Cosa prevedeva il Piano di Pace Arabo 2002?", choices: ["Unione araba", "Normalizzazione per ritiro da territori", "Guerra totale"], a: 1, difficulty: "hard", category: "storia" },
  { q: "Quale fu la causa della Seconda Intifada?", choices: ["Ritiro da Gaza", "Accordi Oslo", "Visita Sharon al Monte del Tempio"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Quale fu il numero di vittime della Nakba (stima)?", choices: ["Centinaia", "Decine", "Migliaia di palestinesi"], a: 2, difficulty: "hard", category: "storia" },


  // MEDIUM (30)
  { q: "Cosa fu la Dichiarazione Balfour (1917)?", choices: ["Trattato di pace", "Promessa britannica per focolare ebraico", "Alleanza militare"], a: 1, difficulty: "medium", category: "storia", explanation: "La Dichiarazione Balfour del 1917 fu una lettera del ministro britannico Arthur Balfour che prometteva un 'focolare nazionale ebraico' in Palestina, territorio allora sotto controllo ottomano.", sources: [{title: "Testo originale Dichiarazione Balfour", url: "https://www.bl.uk/collection-items/balfour-declaration"}, {title: "Analisi storica - The Guardian", url: "https://www.theguardian.com/world/2017/nov/02/balfour-declaration-1917"}] },
  { q: "Cosa prevedeva il Piano ONU del 1947?", choices: ["Annessione all'Egitto", "Stato binazionale", "Due stati: ebraico e arabo"], a: 2, difficulty: "medium", category: "storia", explanation: "La Risoluzione ONU 181 del 1947 prevedeva la partizione della Palestina in due stati: uno ebraico (56% del territorio) e uno arabo (43%), con Gerusalemme sotto amministrazione internazionale.", sources: [{title: "Risoluzione ONU 181", url: "https://www.un.org/unispal/document/auto-insert-179329/"}, {title: "Mappa della partizione", url: "https://www.britannica.com/topic/United-Nations-Resolution-181"}] },
  { q: "Cosa è la 'Nakba' per i palestinesi?", choices: ["Accordi di Oslo", "Esodo palestinese 1948", "Guerra dei Sei Giorni"], a: 1, difficulty: "medium", category: "storia", explanation: "Nakba ('catastrofe' in arabo) indica l'esodo forzato di circa 700.000 palestinesi durante la guerra del 1948. I loro discendenti sono oggi 5-6 milioni di rifugiati.", sources: [{title: "La Nakba spiegata", url: "https://www.aljazeera.com/features/2023/5/15/the-nakba-explained"}, {title: "UNRWA sui rifugiati palestinesi", url: "https://www.unrwa.org/palestine-refugees"}] },
  { q: "Quale guerra del 1967 espanse Israele?", choices: ["Guerra del Kippur", "Guerra dei Sei Giorni", "Guerra del Golfo"], a: 1, difficulty: "medium", category: "storia", explanation: "La Guerra dei Sei Giorni (5-10 giugno 1967) vide Israele conquistare la Cisgiordania, Gaza, le alture del Golan e il Sinai. Questi territori sono ancora oggi al centro del conflitto.", sources: [{title: "Guerra dei Sei Giorni - BBC", url: "https://www.bbc.com/news/world-middle-east-39960461"}, {title: "Documentario - History Channel", url: "https://www.history.com/topics/middle-east/six-day-war"}] },
  { q: "Chi fu Yasser Arafat?", choices: ["Primo ministro israeliano", "Leader dell'OLP", "Presidente egiziano"], a: 1, difficulty: "medium", category: "storia", explanation: "Yasser Arafat (1929-2004) fu il leader dell'OLP dal 1969 e primo presidente dell'Autorità Palestinese. Vinse il Nobel per la Pace nel 1994 insieme a Rabin e Peres per gli Accordi di Oslo.", sources: [{title: "Biografia Arafat - Britannica", url: "https://www.britannica.com/biography/Yasir-Arafat"}, {title: "Nobel Peace Prize 1994", url: "https://www.nobelprize.org/prizes/peace/1994/summary/"}] },
  { q: "Cosa furono gli Accordi di Oslo (1993)?", choices: ["Negoziati di pace israelo-palestinesi", "Accordo UE", "Trattato NATO"], a: 0, difficulty: "medium", category: "storia", explanation: "Gli Accordi di Oslo del 1993 furono negoziati segreti tra Israele e OLP che portarono al riconoscimento reciproco e alla creazione dell'Autorità Palestinese. Yitzhak Rabin, Shimon Peres e Yasser Arafat vinsero il Nobel per la Pace.", sources: [{title: "Oslo Accords - History", url: "https://www.history.com/topics/middle-east/oslo-accords"}, {title: "Testo degli Accordi", url: "https://peacemaker.un.org/israelopt-osloaccord93"}] },
  { q: "Quale movimento controlla Gaza dal 2007?", choices: ["Fatah", "Hezbollah", "Hamas"], a: 2, difficulty: "medium", category: "storia", explanation: "Hamas ('Movimento di Resistenza Islamica') controlla Gaza dal 2007 dopo una guerra civile con Fatah. È considerato un'organizzazione terroristica da USA, UE e Israele, ma un movimento di resistenza dai palestinesi.", sources: [{title: "Chi è Hamas - BBC", url: "https://www.bbc.com/news/world-middle-east-13331522"}, {title: "Hamas e Gaza", url: "https://www.cfr.org/backgrounder/what-hamas"}] },
  { q: "Cosa costruì Israele in Cisgiordania dal 2002?", choices: ["Ferrovia", "Barriera di separazione", "Autostrada"], a: 1, difficulty: "medium", category: "storia", explanation: "Israele ha costruito una barriera di separazione (muro e recinzione) lunga oltre 700 km in Cisgiordania. Israele dice che serve a prevenire attentati, i palestinesi la chiamano 'muro dell'apartheid' che separa famiglie e danneggia l'economia.", sources: [{title: "Il muro della Cisgiordania", url: "https://www.bbc.com/news/world-middle-east-46205357"}, {title: "Corte Internazionale sul muro", url: "https://www.icj-cij.org/en/case/131"}] },
  { q: "Cosa fu la Guerra Fredda?", choices: ["Conflitto nucleare", "Tensione USA-URSS", "Guerra in Asia"], a: 1, difficulty: "medium", category: "storia" },
  { q: "Chi fondò l'Impero Mongolo?", choices: ["Gengis Khan", "Tamerlano", "Kublai Khan"], a: 0, difficulty: "medium", category: "storia" },
  { q: "Quando iniziò la Rivoluzione Francese?", choices: ["1804", "1776", "1789"], a: 2, difficulty: "medium", category: "storia" },
  { q: "Cosa fu il Piano Marshall?", choices: ["Aiuti USA per Europa", "Accordo commerciale", "Piano militare"], a: 0, difficulty: "medium", category: "storia" },
  { q: "Chi fu Winston Churchill?", choices: ["Presidente USA", "Primo ministro britannico", "Leader sovietico"], a: 1, difficulty: "medium", category: "storia" },
  { q: "Quando fu la pace Israele-Egitto?", choices: ["1994", "1993", "1979"], a: 2, difficulty: "medium", category: "storia" },
  { q: "Chi fu il primo premier israeliano?", choices: ["Golda Meir", "Yitzhak Rabin", "David Ben-Gurion"], a: 2, difficulty: "medium", category: "storia", explanation: "David Ben-Gurion (1886-1973) fu il primo Primo Ministro di Israele e uno dei padri fondatori dello Stato. Fu lui a proclamare l'indipendenza di Israele il 14 maggio 1948.", sources: [{title: "Biografia Ben-Gurion", url: "https://www.britannica.com/biography/David-Ben-Gurion"}, {title: "Ben-Gurion Heritage Institute", url: "https://www.bg-heritage.com/"}] },
  { q: "Cosa fu la Prima Intifada?", choices: ["Rivolta palestinese 1987-1993", "Accordi di pace", "Guerra del 1948"], a: 0, difficulty: "medium", category: "storia", explanation: "La Prima Intifada (1987-1993) fu una rivolta popolare palestinese contro l'occupazione israeliana. Caratterizzata da proteste, scioperi e scontri, portò agli Accordi di Oslo e alla creazione dell'Autorità Palestinese.", sources: [{title: "Prima Intifada spiegata", url: "https://www.britannica.com/event/intifada-Palestinian-uprising"}, {title: "30 anni dalla Prima Intifada", url: "https://www.aljazeera.com/features/2017/12/8/the-first-intifada-30-years-on"}] },
  { q: "Chi mediò Camp David?", choices: ["George Bush", "Bill Clinton", "Jimmy Carter"], a: 2, difficulty: "medium", category: "storia" },
  { q: "Quando iniziò la Seconda Intifada?", choices: ["2000", "1995", "2005"], a: 0, difficulty: "medium", category: "storia", explanation: "La Seconda Intifada iniziò nel settembre 2000 dopo la visita di Ariel Sharon alla Spianata delle Moschee. Fu molto più violenta della prima, con attentati suicidi e operazioni militari. Causò migliaia di morti da entrambe le parti.", sources: [{title: "Seconda Intifada - BBC", url: "https://www.bbc.com/news/world-middle-east-14630174"}, {title: "Al-Aqsa Intifada", url: "https://www.britannica.com/event/al-Aqsa-intifada"}] },
  { q: "Chi fu ucciso dopo Oslo?", choices: ["Shimon Peres", "Yitzhak Rabin", "Menachem Begin"], a: 1, difficulty: "medium", category: "storia", explanation: "Yitzhak Rabin, Primo Ministro israeliano e firmatario degli Accordi di Oslo, fu assassinato il 4 novembre 1995 da un estremista ebraico israeliano che si opponeva al processo di pace.", sources: [{title: "Assassinio di Rabin", url: "https://www.britannica.com/biography/Yitzhak-Rabin"}, {title: "L'eredità di Rabin - NYT", url: "https://www.nytimes.com/topic/person/yitzhak-rabin"}] },
  { q: "Quale impero controllò la Terra Santa 400 anni?", choices: ["Impero Bizantino", "Impero Persiano", "Impero Ottomano"], a: 2, difficulty: "medium", category: "storia", explanation: "L'Impero Ottomano controllò la Palestina dal 1517 al 1917, per quattro secoli. Cadde nella Prima Guerra Mondiale e il territorio passò sotto mandato britannico.", sources: [{title: "Palestina ottomana", url: "https://www.britannica.com/place/Palestine/Ottoman-rule"}, {title: "Fine Impero Ottomano", url: "https://www.treccani.it/enciclopedia/impero-ottomano"}] },
  { q: "Cosa fu Piombo Fuso?", choices: ["Accordo di pace", "Evacuazione colonie", "Operazione Gaza 2008-2009"], a: 2, difficulty: "medium", category: "storia" },
  { q: "Chi fu Theodor Herzl?", choices: ["Generale britannico", "Leader palestinese", "Fondatore sionismo"], a: 2, difficulty: "medium", category: "storia", explanation: "Theodor Herzl (1860-1904) fu il fondatore del sionismo politico moderno. Nel 1896 pubblicò 'Lo Stato Ebraico' e nel 1897 organizzò il Primo Congresso Sionista a Basilea, ponendo le basi per la futura creazione di Israele.", sources: [{title: "Biografia Herzl", url: "https://www.britannica.com/biography/Theodor-Herzl"}, {title: "Lo Stato Ebraico", url: "https://www.jewishvirtuallibrary.org/quot-the-jewish-state-quot-theodor-herzl"}] },
  { q: "Quando Israele evacuò Gaza?", choices: ["2000", "2010", "2005"], a: 2, difficulty: "medium", category: "storia", explanation: "Nel 2005 Israele evacuò unilateralmente tutti i 21 insediamenti israeliani da Gaza e 4 dal nord della Cisgiordania. Fu una decisione controversa del primo ministro Ariel Sharon. Nel 2007 Hamas prese il controllo di Gaza.", sources: [{title: "Disimpegno da Gaza", url: "https://www.britannica.com/event/Israeli-disengagement-from-Gaza"}, {title: "Gaza 2005 - BBC", url: "https://www.bbc.com/news/world-middle-east-34643324"}] },
  { q: "Quale paese arabo firmò pace nel 1994?", choices: ["Siria", "Giordania", "Libano"], a: 1, difficulty: "medium", category: "storia", explanation: "La Giordania firmò un trattato di pace con Israele nell'ottobre 1994, diventando il secondo paese arabo a farlo dopo l'Egitto (1979). Il re Hussein e il primo ministro Rabin normalizzarono le relazioni tra i due paesi.", sources: [{title: "Pace Israele-Giordania", url: "https://www.britannica.com/event/Israel-Jordan-Peace-Treaty"}, {title: "Trattato 1994", url: "https://www.mfa.gov.il/mfa/foreignpolicy/mfadocuments/yearbook9/pages/115%20israel-jordan%20peace%20treaty.aspx"}] },
  { q: "Cosa furono gli Accordi di Abraham?", choices: ["Normalizzazione Israele-arabi 2020", "Trattato ONU", "Accordi 1948"], a: 0, difficulty: "medium", category: "storia", explanation: "Gli Accordi di Abraham (2020) normalizzarono le relazioni tra Israele e alcuni paesi arabi (Emirati Arabi, Bahrein, Sudan, Marocco) sotto mediazione USA. Furono controversi perché non richiedevano progressi sul conflitto palestinese.", sources: [{title: "Abraham Accords - CFR", url: "https://www.cfr.org/backgrounder/what-are-abraham-accords"}, {title: "Analisi Accordi - BBC", url: "https://www.bbc.com/news/world-middle-east-54124996"}] },
  { q: "Chi fu Golda Meir?", choices: ["Prima ministra israeliana", "Leader OLP", "Presidente egiziano"], a: 0, difficulty: "medium", category: "storia" },
  { q: "Capitale Autorità Palestinese?", choices: ["Ramallah", "Nablus", "Gaza"], a: 0, difficulty: "medium", category: "storia" },
  { q: "Quando fu la Guerra del Kippur?", choices: ["1967", "1973", "1982"], a: 1, difficulty: "medium", category: "storia" },
  { q: "Chi fu Menachem Begin?", choices: ["Premier israeliano, pace con Egitto", "Leader laburista", "Generale"], a: 0, difficulty: "medium", category: "storia" },
  { q: "Quale operazione evacuò ebrei etiopi?", choices: ["Operazione Mosè e Salomone", "Operazione Entebbe", "Operazione Piombo"], a: 0, difficulty: "medium", category: "storia" },

  // HARD (30)
  { q: "Quale evento iniziò la guerra del 1948?", choices: ["Fine Mandato e proclamazione Israele", "Guerra Sei Giorni", "Dichiarazione Balfour"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Ruolo Risoluzione 181 ONU?", choices: ["Propose partizione in due stati", "Revocò Mandato", "Creò stato unico"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Cosa catturò Israele nel 1967?", choices: ["Solo Sinai", "Sinai, Gaza, Cisgiordania, Golan", "Solo Gaza"], a: 1, difficulty: "hard", category: "storia" },
  { q: "Cosa propone 'two-state solution'?", choices: ["Due stati separati", "Federazione unica", "Annessione completa"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Significato storico Intifada?", choices: ["Sollevazione palestinese", "Trattato di pace", "Guerra araba"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Chi controllava Palestina pre-Mandato?", choices: ["Impero Persiano", "Impero Romano", "Impero Ottomano"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Quale Risoluzione chiese ritiro 1967?", choices: ["Risoluzione 242", "Risoluzione 194", "Risoluzione 181"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Cosa fu Risoluzione 194 ONU?", choices: ["Diritto ritorno rifugiati", "Creazione Israele", "Partizione Palestina"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Chi fu Ariel Sharon?", choices: ["Leader OLP", "Generale e premier israeliano", "Mediatore ONU"], a: 1, difficulty: "hard", category: "storia" },
  { q: "Cosa fu Operazione Entebbe?", choices: ["Guerra Libano", "Operazione Gaza", "Raid Uganda ostaggi 1976"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Origini di Hamas?", choices: ["Hezbollah", "Al-Qaeda", "Ramo Fratelli Musulmani"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Cosa furono Sabra e Shatila?", choices: ["Battaglia Kippur", "Rivolta Gaza", "Massacri campi profughi Libano 1982"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Chi è Mahmoud Abbas?", choices: ["Leader Hamas", "Presidente Autorità Palestinese", "Segretario ONU"], a: 1, difficulty: "hard", category: "storia" },
  { q: "Libro Bianco britannico 1939?", choices: ["Limitò immigrazione ebraica", "Dichiarazione guerra", "Accordo pace"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Piano Pace Arabo 2002?", choices: ["Annessione", "Normalizzazione per ritiro 1967", "Guerra totale"], a: 1, difficulty: "hard", category: "storia" },
  { q: "Chi fondò Fatah?", choices: ["Yasser Arafat", "Mahmoud Abbas", "Ahmed Yassin"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Cosa fu accordo Wye River?", choices: ["Accordo israelo-palestinese 1998", "Trattato Giordania", "Accordo Egitto"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Nobel Pace 1994?", choices: ["Netanyahu", "Rabin, Peres, Arafat", "Sharon"], a: 1, difficulty: "hard", category: "storia" },
  { q: "Guerra Mille Giorni Libano?", choices: ["Invasione israeliana 1982-1985", "Guerra civile", "Conflitto Siria"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Paese con più rifugiati palestinesi?", choices: ["Giordania", "Siria", "Libano"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Cosa fu Congresso Vienna?", choices: ["Riorganizzazione Europa post-napoleonica", "Trattato pace mondiale", "Accordo commerciale"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Chi fu Otto von Bismarck?", choices: ["Re inglese", "Cancelliere prussiano unificatore", "Imperatore austriaco"], a: 1, difficulty: "hard", category: "storia" },
  { q: "Trattati Westfalia 1648?", choices: ["Inizio WWI", "Caduta impero romano", "Fine Guerra Trent'anni"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Chi fu Garibaldi?", choices: ["Eroe unificazione italiana", "Leader francese", "Generale prussiano"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Quale guerra iniziò in Corea?", choices: ["1950", "1945", "1953"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Chi fu Stalin?", choices: ["Leader sovietico", "Presidente USA", "Re inglese"], a: 0, difficulty: "hard", category: "storia" },
  { q: "Quando fu Rivoluzione Russa?", choices: ["1920", "1905", "1917"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Chi fu Mao Zedong?", choices: ["Premier indiano", "Imperatore giapponese", "Leader comunista cinese"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Cosa fu Trattato Versailles?", choices: ["Fine WWII", "Pace napoleonica", "Fine WWI"], a: 2, difficulty: "hard", category: "storia" },
  { q: "Chi fu Nelson Mandela?", choices: ["Presidente USA", "Leader anti-apartheid sudafricano", "Premier britannico"], a: 1, difficulty: "hard", category: "storia" },

  // ==================== INFORMATICA ====================
  // EASY (25)
  { q: "Cos'è un bit?", choices: ["Tipo tastiera", "Linguaggio programmazione", "Unità binaria (0 o 1)"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Chi sviluppò il linguaggio C?", choices: ["Bjarne Stroustrup", "Bill Gates", "Dennis Ritchie"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Cos'è un browser?", choices: ["Tipo processore", "Dispositivo rete", "Programma per navigare web"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Sistema operativo più diffuso?", choices: ["JPEG", "Windows", "HTML"], a: 1, difficulty: "easy", category: "informatica" },
  { q: "Significato HTTP?", choices: ["High Transfer Text", "Hyperlink Terminal", "HyperText Transfer Protocol"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Chi inventò il World Wide Web?", choices: ["Tim Berners-Lee", "Alan Turing", "Steve Jobs"], a: 0, difficulty: "easy", category: "informatica" },
  { q: "Significato RAM?", choices: ["Random Access Memory", "Read After Memory", "Remote Access"], a: 0, difficulty: "easy", category: "informatica" },
  { q: "Cos'è un algoritmo?", choices: ["Disco fisso", "Componente CPU", "Sequenza istruzioni"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Significato CPU?", choices: ["Central Program", "Computer Program", "Central Processing Unit"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Quale è un motore di ricerca?", choices: ["Excel", "Photoshop", "Google"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Quanti bit in un byte?", choices: ["8", "4", "16"], a: 0, difficulty: "easy", category: "informatica" },
  { q: "Significato LED?", choices: ["Light Emitting Diode", "Long Energy Device", "Light Electric"], a: 0, difficulty: "easy", category: "informatica" },
  { q: "Tecnologia wireless a corto raggio?", choices: ["Ethernet", "USB-C", "Bluetooth"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Cosa fa un firewall?", choices: ["Protegge rete", "Raffredda PC", "Stampa documenti"], a: 0, difficulty: "easy", category: "informatica" },
  { q: "Come si diffondono info sul conflitto online?", choices: ["Solo radio", "Social media e news", "Solo TV"], a: 1, difficulty: "easy", category: "informatica" },
  { q: "Cos'è Linux?", choices: ["Sistema operativo open source", "Linguaggio programmazione", "Browser web"], a: 0, difficulty: "easy", category: "informatica" },
  { q: "Significato URL?", choices: ["Uniform Resource Locator", "Universal Read Link", "User Remote Location"], a: 0, difficulty: "easy", category: "informatica" },
  { q: "Cos'è un virus informatico?", choices: ["Tipo processore", "Componente hardware", "Software malevolo"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Linguaggio per pagine web?", choices: ["Java", "Python", "HTML"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Cos'è ROM?", choices: ["Random Output Memory", "Remote Operating", "Read-Only Memory"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Piattaforma per video sul conflitto?", choices: ["Solo SMS", "Solo Email", "YouTube, TikTok, Twitter"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Cos'è un megabyte?", choices: ["1000 byte", "1 miliardo byte", "Circa 1 milione byte"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Cosa fa Ctrl+C?", choices: ["Incolla", "Taglia", "Copia"], a: 2, difficulty: "easy", category: "informatica" },
  { q: "Cos'è file ZIP?", choices: ["Programma", "File compresso", "Tipo immagine"], a: 1, difficulty: "easy", category: "informatica" },
  { q: "Tecnologia per videochiamate documentare eventi?", choices: ["Solo lettere", "VoIP e videoconferenza", "Solo telefoni fissi"], a: 1, difficulty: "easy", category: "informatica" },

  // MEDIUM (25)
  { q: "Cos'è OOP?", choices: ["Database", "Paradigma oggetti e classi", "Sistema operativo"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Protocollo per email?", choices: ["FTP", "SMTP", "SSH"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Significato 'open source'?", choices: ["Software chiuso", "Codice liberamente accessibile", "Software a pagamento"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Linguaggio per machine learning?", choices: ["Python", "HTML", "CSS"], a: 0, difficulty: "medium", category: "informatica" },
  { q: "Ricerca efficiente in array ordinato?", choices: ["Ricerca lineare O(n)", "Ricerca binaria O(log n)", "Bubble sort"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Significato LAN?", choices: ["Lightweight Access", "Large Application", "Local Area Network"], a: 2, difficulty: "medium", category: "informatica" },
  { q: "Chi teorizzò computer programmabile?", choices: ["Alan Turing", "Charles Babbage", "John von Neumann"], a: 0, difficulty: "medium", category: "informatica" },
  { q: "Cos'è deadlock?", choices: ["Linguaggio obsoleto", "Processi bloccati in attesa reciproca", "Processo terminato"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Cos'è SQL?", choices: ["Sistema operativo", "Linguaggio per database", "Linguaggio web"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Cosa fa compilatore?", choices: ["Esegue programmi", "Traduce codice in linguaggio macchina", "Cancella file"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Come tecnologia documenta conflitto?", choices: ["Solo TV", "Foto, video, social media", "Solo giornali"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Cos'è hash?", choices: ["Protocollo rete", "Funzione mappa dati a valore fisso", "Tipo virus"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Significato API?", choices: ["Application Programming Interface", "Advanced Program", "Automated Process"], a: 0, difficulty: "medium", category: "informatica" },
  { q: "Cos'è cloud computing?", choices: ["Servizi IT via internet", "Tipo hardware", "Software locale"], a: 0, difficulty: "medium", category: "informatica" },
  { q: "Cosa fa Git?", choices: ["Controllo versione codice", "Naviga web", "Modifica immagini"], a: 0, difficulty: "medium", category: "informatica" },
  { q: "Cos'è crittografia?", choices: ["Tecnica proteggere dati", "Tipo virus", "Linguaggio programmazione"], a: 0, difficulty: "medium", category: "informatica" },
  { q: "Significato DNS?", choices: ["Digital Name Service", "Domain Name System", "Data Network Server"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Cos'è cookie?", choices: ["Tipo virus", "File per tracciare utenti web", "Componente hardware"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Tecnologia israeliana in cybersecurity?", choices: ["Firewall e antivirus avanzati", "Solo hardware", "Solo giochi"], a: 0, difficulty: "medium", category: "informatica" },
  { q: "Cos'è JavaScript?", choices: ["Database", "Sistema operativo", "Linguaggio programmazione web"], a: 2, difficulty: "medium", category: "informatica" },
  { q: "Significato VPN?", choices: ["Virtual Private Network", "Video Program", "Very Private Network"], a: 0, difficulty: "medium", category: "informatica" },
  { q: "Cos'è server?", choices: ["Tipo processore", "Computer che fornisce servizi", "Programma grafico"], a: 1, difficulty: "medium", category: "informatica" },
  { q: "Censura online in zone conflitto?", choices: ["Solo avvisi", "Non censurata", "Blocco siti, throttling, shutdown"], a: 2, difficulty: "medium", category: "informatica" },
  { q: "Cos'è machine learning?", choices: ["Apprendimento automatico AI", "Sistema operativo", "Linguaggio programmazione"], a: 0, difficulty: "medium", category: "informatica" },
  { q: "Significato IP?", choices: ["Internet Protocol", "Information Process", "Internal Program"], a: 0, difficulty: "medium", category: "informatica" },

  // HARD (20)
  { q: "Classe problemi tempo polinomiale?", choices: ["P", "EXPTIME", "NP"], a: 0, difficulty: "hard", category: "informatica" },
  { q: "Cos'è complessità spaziale?", choices: ["Memoria in funzione input", "Parallelismo", "Tempo esecuzione"], a: 0, difficulty: "hard", category: "informatica" },
  { q: "RSA in crittografia?", choices: ["Sistema chiave pubblica", "Algoritmo simmetrico", "Protocollo rete"], a: 0, difficulty: "hard", category: "informatica" },
  { q: "Normalizzazione database?", choices: ["Organizzare dati ridurre ridondanza", "Crittografia", "Replica dati"], a: 0, difficulty: "hard", category: "informatica" },
  { q: "Teorema Church-Turing?", choices: ["P = NP", "Funzioni calcolabili macchina Turing", "Macchine inefficienti"], a: 1, difficulty: "hard", category: "informatica" },
  { q: "Cos'è overfitting?", choices: ["Dataset piccolo", "Modello troppo adattato training", "Modello generalizza troppo"], a: 1, difficulty: "hard", category: "informatica" },
  { q: "Backpropagation?", choices: ["Algoritmo training reti neurali", "Protocollo rete", "Tipo database"], a: 0, difficulty: "hard", category: "informatica" },
  { q: "Algoritmo Dijkstra?", choices: ["Ordina liste", "Comprime file", "Percorso più breve grafo"], a: 2, difficulty: "hard", category: "informatica" },
  { q: "AI analizza sentiment conflitto?", choices: ["Non può", "Natural Language Processing", "Solo conteggio parole"], a: 1, difficulty: "hard", category: "informatica" },
  { q: "Problema NP-completo?", choices: ["In NP e NP-hard", "Non risolvibile", "In P"], a: 0, difficulty: "hard", category: "informatica" },
  { q: "Teorema CAP database?", choices: ["Solo velocità", "Consistency, Availability, Partition tolerance", "Solo sicurezza"], a: 1, difficulty: "hard", category: "informatica" },
  { q: "Cos'è blockchain?", choices: ["File compresso", "Registro distribuito immutabile", "Database normale"], a: 1, difficulty: "hard", category: "informatica" },
  { q: "Algoritmo consensus Paxos?", choices: ["Crittografia", "Accordo distribuito", "Ordinamento"], a: 1, difficulty: "hard", category: "informatica" },
  { q: "Cos'è Big O notation?", choices: ["Tipo database", "Complessità algoritmo", "Linguaggio programmazione"], a: 1, difficulty: "hard", category: "informatica" },
  { q: "MapReduce?", choices: ["Protocollo rete", "Algoritmo ordinamento", "Paradigma elaborazione distribuita"], a: 2, difficulty: "hard", category: "informatica" },
  { q: "Tecnologia israeliana Unit 8200?", choices: ["Solo videogiochi", "Solo social media", "Intelligenza cyber militare"], a: 2, difficulty: "hard", category: "informatica" },
  { q: "Cos'è proof of work?", choices: ["Protocollo email", "Meccanismo consensus blockchain", "Algoritmo crittografia"], a: 1, difficulty: "hard", category: "informatica" },
  { q: "Lambda calculus?", choices: ["Database", "Sistema formale computazione", "Linguaggio programmazione"], a: 1, difficulty: "hard", category: "informatica" },
  { q: "ACID proprietà database?", choices: ["Solo velocità", "Solo sicurezza", "Atomicity, Consistency, Isolation, Durability"], a: 2, difficulty: "hard", category: "informatica" },
  { q: "Cos'è Byzantine fault tolerance?", choices: ["Tolleranza guasti sistemi distribuiti", "Protocollo rete", "Tipo crittografia"], a: 0, difficulty: "hard", category: "informatica" },

  // ==================== SCIENZA ====================
  // EASY (25)
  { q: "Formula acqua?", choices: ["H2O", "NaCl", "CO2"], a: 0, difficulty: "easy", category: "scienza" },
  { q: "Cos'è DNA?", choices: ["Tipo cellula", "Materiale plastico", "Acido desossiribonucleico"], a: 2, difficulty: "easy", category: "scienza" },
  { q: "Pianeta rosso?", choices: ["Giove", "Venere", "Marte"], a: 2, difficulty: "easy", category: "scienza" },
  { q: "Simbolo ossigeno?", choices: ["Os", "Au", "O"], a: 2, difficulty: "easy", category: "scienza" },
  { q: "Chi propose relatività?", choices: ["Einstein", "Newton", "Tesla"], a: 0, difficulty: "easy", category: "scienza" },
  { q: "Gas respirato umani?", choices: ["CO2", "Ossigeno", "Azoto"], a: 1, difficulty: "easy", category: "scienza" },
  { q: "Unità corrente elettrica?", choices: ["Ampere", "Ohm", "Volt"], a: 0, difficulty: "easy", category: "scienza" },
  { q: "Organo pompa sangue?", choices: ["Cuore", "Polmoni", "Fegato"], a: 0, difficulty: "easy", category: "scienza" },
  { q: "Voltmetro misura?", choices: ["Resistenza", "Corrente", "Tensione"], a: 2, difficulty: "easy", category: "scienza" },
  { q: "Fonte energia piante?", choices: ["CO2", "Azoto", "Luce solare"], a: 2, difficulty: "easy", category: "scienza" },
  { q: "Gas più leggero aria?", choices: ["CO2", "Argon", "Elio"], a: 2, difficulty: "easy", category: "scienza" },
  { q: "Dove materiale genetico?", choices: ["Mitocondrio", "Nucleo", "Cloroplasto"], a: 1, difficulty: "easy", category: "scienza" },
  { q: "Temperatura ebollizione acqua?", choices: ["50°C", "212°C", "100°C"], a: 2, difficulty: "easy", category: "scienza" },
  { q: "Scienza studia clima regione?", choices: ["Chimica", "Astronomia", "Climatologia"], a: 2, difficulty: "easy", category: "scienza" },
  { q: "Quanti sensi umani?", choices: ["5", "4", "6"], a: 0, difficulty: "easy", category: "scienza" },
  { q: "Pianeta più grande?", choices: ["Saturno", "Giove", "Terra"], a: 1, difficulty: "easy", category: "scienza" },
  { q: "Cosa producono piante?", choices: ["Idrogeno", "Azoto", "Ossigeno"], a: 2, difficulty: "easy", category: "scienza" },
  { q: "Unità misura forza?", choices: ["Newton", "Watt", "Joule"], a: 0, difficulty: "easy", category: "scienza" },
  { q: "Quanti cromosomi umani?", choices: ["48", "23", "46"], a: 2, difficulty: "easy", category: "scienza" },
  { q: "Velocità della luce?", choices: ["150.000 km/s", "300.000 km/s", "500.000 km/s"], a: 1, difficulty: "easy", category: "scienza" },
  { q: "Cosa studia botanica?", choices: ["Rocce", "Piante", "Animali"], a: 1, difficulty: "easy", category: "scienza" },
  { q: "Quale elemento più abbondante?", choices: ["Carbonio", "Idrogeno", "Ossigeno"], a: 1, difficulty: "easy", category: "scienza" },
  { q: "Cos'è fotosintesi?", choices: ["Produzione glucosio da luce", "Respirazione", "Digestione"], a: 0, difficulty: "easy", category: "scienza" },
  { q: "Quante ossa corpo umano?", choices: ["300", "206", "150"], a: 1, difficulty: "easy", category: "scienza" },
  { q: "Risorsa contesa nella regione?", choices: ["Acqua", "Oro", "Petrolio"], a: 0, difficulty: "easy", category: "scienza" },

  // MEDIUM (25)
  { q: "Legge gravitazione?", choices: ["Newton", "Coulomb", "Ohm"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Cos'è entropia?", choices: ["Pressione gas", "Velocità reazione", "Misura disordine"], a: 2, difficulty: "medium", category: "scienza" },
  { q: "Divisione produce gameti?", choices: ["Meiosi", "Fissione", "Mitosi"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Cos'è esopianeta?", choices: ["Asteroide", "Pianeta extra-solare", "Pianeta sistema solare"], a: 1, difficulty: "medium", category: "scienza" },
  { q: "Principio effetto Doppler?", choices: ["Diffrazione luce", "Variazione frequenza per moto", "Polarizzazione"], a: 1, difficulty: "medium", category: "scienza" },
  { q: "Chi propose modello eliocentrico?", choices: ["Copernico", "Pitagora", "Aristotele"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Cos'è gene?", choices: ["Segmento DNA", "Cellula", "Proteina"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Prima legge termodinamica?", choices: ["Zero assoluto", "Conservazione energia", "Entropia"], a: 1, difficulty: "medium", category: "scienza" },
  { q: "Legge Ohm?", choices: ["E = mc²", "V = I × R", "F = ma"], a: 1, difficulty: "medium", category: "scienza" },
  { q: "Cos'è catalizzatore?", choices: ["Riduce energia attivazione", "Aumenta temperatura", "Viene consumato"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Processo produce ATP?", choices: ["Fermentazione", "Respirazione cellulare", "Fotosintesi"], a: 1, difficulty: "medium", category: "scienza" },
  { q: "Risorsa idrica contesa?", choices: ["Oro", "Acqua", "Petrolio"], a: 1, difficulty: "medium", category: "scienza" },
  { q: "Scala Richter misura?", choices: ["Velocità vento", "Temperatura", "Magnitudo terremoti"], a: 2, difficulty: "medium", category: "scienza" },
  { q: "Cos'è isotopo?", choices: ["Atomi stesso elemento diversi neutroni", "Molecole", "Atomi diversi elementi"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Cos'è quark?", choices: ["Particella elementare", "Molecola", "Tipo atomo"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Chi scoprì radioattività?", choices: ["Einstein", "Becquerel e Curie", "Newton"], a: 1, difficulty: "medium", category: "scienza" },
  { q: "Cos'è glucosio?", choices: ["Proteina", "Zucchero semplice", "Lipide"], a: 1, difficulty: "medium", category: "scienza" },
  { q: "Cosa studia geologia?", choices: ["Vita", "Terra e rocce", "Stelle"], a: 1, difficulty: "medium", category: "scienza" },
  { q: "Cos'è neutrino?", choices: ["Gas", "Tipo stella", "Particella subatomica"], a: 2, difficulty: "medium", category: "scienza" },
  { q: "Chi teorizzò evoluzione?", choices: ["Darwin", "Mendel", "Lamarck"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Cos'è plasma?", choices: ["Tipo cellula", "Quarto stato materia", "Gas"], a: 1, difficulty: "medium", category: "scienza" },
  { q: "Tecnologia desalinizzazione in Israele?", choices: ["Osmosi inversa avanzata", "Solo ebollizione", "Solo filtri"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Cos'è fotone?", choices: ["Particella luce", "Tipo atomo", "Gas"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Scala pH misura?", choices: ["Acidità/basicità", "Temperatura", "Pressione"], a: 0, difficulty: "medium", category: "scienza" },
  { q: "Cos'è enzima?", choices: ["Proteina catalizzatrice", "Sostanza inorganica", "Carboidrato"], a: 0, difficulty: "medium", category: "scienza" },

  // HARD (20)
  { q: "Effetto Cherenkov?", choices: ["Radiazione termica", "Luce particella oltre velocità luce mezzo", "Effetto fotoelettrico"], a: 1, difficulty: "hard", category: "scienza" },
  { q: "Principio indeterminazione?", choices: ["Fotoni correlati", "Energia conserva", "Non si può conoscere posizione e momento simultaneamente"], a: 2, difficulty: "hard", category: "scienza" },
  { q: "Particella mediatrice elettromagnetismo?", choices: ["Gluone", "Fotone", "Bosone W"], a: 1, difficulty: "hard", category: "scienza" },
  { q: "Teorema Bayes?", choices: ["P(A|B)=P(A)-P(B)", "P(A∩B)=P(A)+P(B)", "P(A|B) = P(B|A)P(A)/P(B)"], a: 2, difficulty: "hard", category: "scienza" },
  { q: "Principio esclusione Pauli?", choices: ["Due fermioni non stesso stato", "Indeterminazione", "Sovrapposizione"], a: 0, difficulty: "hard", category: "scienza" },
  { q: "Cos'è entalpia?", choices: ["Energia cinetica", "Energia potenziale", "H = U + PV"], a: 2, difficulty: "hard", category: "scienza" },
  { q: "Teorema Noether?", choices: ["Energia non conserva", "Simmetria implica conservazione", "Velocità luce variabile"], a: 1, difficulty: "hard", category: "scienza" },
  { q: "Tecnologia medica israeliana avanzata?", choices: ["Solo chirurgia", "Solo farmaci", "Imaging e biotecnologie"], a: 2, difficulty: "hard", category: "scienza" },
  { q: "Equazione Navier-Stokes?", choices: ["Onde elettromagnetiche", "Moto fluidi viscosi", "Circuiti elettrici"], a: 1, difficulty: "hard", category: "scienza" },
  { q: "Cos'è bosone Higgs?", choices: ["Tipo stella", "Gas", "Particella dà massa"], a: 2, difficulty: "hard", category: "scienza" },
  { q: "Equazioni Maxwell?", choices: ["Elettromagnetismo", "Gravità", "Termodinamica"], a: 0, difficulty: "hard", category: "scienza" },
  { q: "Costante Planck?", choices: ["c = 3×10⁸ m/s", "G = 6.67×10⁻¹¹", "h = 6.626×10⁻³⁴ J·s"], a: 2, difficulty: "hard", category: "scienza" },
  { q: "Cos'è quasar?", choices: ["Tipo stella", "Nucleo galattico attivo", "Pianeta"], a: 1, difficulty: "hard", category: "scienza" },
  { q: "Paradosso EPR?", choices: ["Relatività", "Entanglement quantistico", "Termodinamica"], a: 1, difficulty: "hard", category: "scienza" },
  { q: "Costante Avogadro?", choices: ["3×10⁸ m/s", "6.022×10²³ mol⁻¹", "9.81 m/s²"], a: 1, difficulty: "hard", category: "scienza" },
  { q: "Equazione Schrödinger?", choices: ["Meccanica quantistica", "Relatività", "Termodinamica"], a: 0, difficulty: "hard", category: "scienza" },
  { q: "Cos'è materia oscura?", choices: ["Gas", "Tipo stella", "Materia non emette luce"], a: 2, difficulty: "hard", category: "scienza" },
  { q: "Teoria delle stringhe?", choices: ["Particelle come stringhe vibranti", "Relatività", "Gravità quantistica"], a: 0, difficulty: "hard", category: "scienza" },
  { q: "Cos'è superconduttività?", choices: ["Alta resistenza", "Resistenza zero a basse temperature", "Isolamento"], a: 1, difficulty: "hard", category: "scienza" },
  { q: "Radiazione Hawking?", choices: ["Radiazione buchi neri", "Radiazione stelle", "Radiazione solare"], a: 0, difficulty: "hard", category: "scienza" },

  // ==================== GEOGRAFIA ====================
  // EASY (25)
  { q: "Capitale Italia?", choices: ["Roma", "Milano", "Firenze"], a: 0, difficulty: "easy", category: "geografia" },
  { q: "Fiume più lungo mondo?", choices: ["Nilo", "Mississippi", "Amazzonia"], a: 0, difficulty: "easy", category: "geografia" },
  { q: "Valuta Giappone?", choices: ["Yen", "Euro", "Dollaro"], a: 0, difficulty: "easy", category: "geografia" },
  { q: "Gas principale atmosfera?", choices: ["Ossigeno", "Azoto", "CO2"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Unità base lunghezza?", choices: ["Metro", "Piede", "Yarda"], a: 0, difficulty: "easy", category: "geografia" },
  { q: "Continente più grande?", choices: ["Europa", "Asia", "Africa"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Capitale Francia?", choices: ["Londra", "Parigi", "Berlino"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Continente Israele e Palestina?", choices: ["Europa", "Asia", "Africa"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Montagna più alta?", choices: ["K2", "Everest", "Kilimangiaro"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Oceano più grande?", choices: ["Atlantico", "Pacifico", "Indiano"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Quanti continenti?", choices: ["6", "7", "5"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Deserto confina con Israele?", choices: ["Sahara", "Gobi", "Negev"], a: 2, difficulty: "easy", category: "geografia" },
  { q: "Capitale Spagna?", choices: ["Madrid", "Valencia", "Barcellona"], a: 0, difficulty: "easy", category: "geografia" },
  { q: "Linea divide la Terra?", choices: ["Meridiano", "Tropico", "Equatore"], a: 2, difficulty: "easy", category: "geografia" },
  { q: "Stato più popoloso?", choices: ["India", "USA", "Cina"], a: 2, difficulty: "easy", category: "geografia" },
  { q: "Capitale Germania?", choices: ["Amburgo", "Monaco", "Berlino"], a: 2, difficulty: "easy", category: "geografia" },
  { q: "Quale mare è più salato?", choices: ["Mar Rosso", "Mar Mediterraneo", "Mar Morto"], a: 2, difficulty: "easy", category: "geografia" },
  { q: "Quanti stati USA?", choices: ["48", "52", "50"], a: 2, difficulty: "easy", category: "geografia" },
  { q: "Capitale Egitto?", choices: ["Il Cairo", "Luxor", "Alessandria"], a: 0, difficulty: "easy", category: "geografia" },
  { q: "Montagna più alta Europa?", choices: ["Monte Rosa", "Monte Bianco", "Matterhorn"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Fiume più lungo Europa?", choices: ["Danubio", "Volga", "Reno"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Capitale Giappone?", choices: ["Tokyo", "Kyoto", "Osaka"], a: 0, difficulty: "easy", category: "geografia" },
  { q: "Isola più grande Mediterraneo?", choices: ["Creta", "Sicilia", "Sardegna"], a: 1, difficulty: "easy", category: "geografia" },
  { q: "Quale città non è sul mare?", choices: ["Barcellona", "Valencia", "Madrid"], a: 2, difficulty: "easy", category: "geografia" },
  { q: "Capitale Russia?", choices: ["Kiev", "San Pietroburgo", "Mosca"], a: 2, difficulty: "easy", category: "geografia" },

  // MEDIUM (25)
  { q: "Capitale Australia?", choices: ["Melbourne", "Sydney", "Canberra"], a: 2, difficulty: "medium", category: "geografia" },
  { q: "Fiume attraversa Egitto?", choices: ["Tigri", "Eufrate", "Nilo"], a: 2, difficulty: "medium", category: "geografia" },
  { q: "Quanti paesi confinano Israele?", choices: ["2", "6", "4 (Libano, Siria, Giordania, Egitto)"], a: 2, difficulty: "medium", category: "geografia" },
  { q: "Stretto Africa-Europa?", choices: ["Gibilterra", "Bering", "Hormuz"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Paese più piccolo mondo?", choices: ["Vaticano", "San Marino", "Monaco"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Mare a est Israele?", choices: ["Mar Rosso", "Mar Nero", "Mar Morto"], a: 2, difficulty: "medium", category: "geografia" },
  { q: "Catena montuosa più lunga?", choices: ["Ande", "Alpi", "Himalaya"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Capitale Canada?", choices: ["Toronto", "Ottawa", "Vancouver"], a: 1, difficulty: "medium", category: "geografia" },
  { q: "Isola più grande mondo?", choices: ["Nuova Guinea", "Groenlandia", "Borneo"], a: 1, difficulty: "medium", category: "geografia" },
  { q: "Città divisa nel conflitto?", choices: ["Gerusalemme", "Tel Aviv", "Haifa"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Lago più profondo?", choices: ["Superiore", "Baikal", "Vittoria"], a: 1, difficulty: "medium", category: "geografia" },
  { q: "Fusi orari Russia?", choices: ["11", "7", "9"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Dove si trova Mar Morto?", choices: ["Tra Israele, Palestina e Giordania", "Siria", "Egitto"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Vulcano più alto Europa?", choices: ["Etna", "Vesuvio", "Stromboli"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Fiume USA-Messico?", choices: ["Rio Grande", "Colorado", "Mississippi"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Capitale Brasile?", choices: ["Brasília", "Rio de Janeiro", "San Paolo"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Deserto più grande?", choices: ["Sahara", "Kalahari", "Gobi"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Paese attraversato da Equatore?", choices: ["Perù", "Colombia", "Ecuador"], a: 2, difficulty: "medium", category: "geografia" },
  { q: "Capitale Turchia?", choices: ["Smirne", "Ankara", "Istanbul"], a: 1, difficulty: "medium", category: "geografia" },
  { q: "Mare separa Italia Grecia?", choices: ["Mar Ionio", "Mar Egeo", "Mar Adriatico"], a: 0, difficulty: "medium", category: "geografia" },
  { q: "Quanti stati confinavano Palestina storica?", choices: ["5", "4", "3"], a: 1, difficulty: "medium", category: "geografia" },
  { q: "Capitale Olanda?", choices: ["L'Aia", "Rotterdam", "Amsterdam"], a: 2, difficulty: "medium", category: "geografia" },
  { q: "Fiume più lungo Asia?", choices: ["Gange", "Mekong", "Yangtze"], a: 2, difficulty: "medium", category: "geografia" },
  { q: "Penisola dove si trova Israele?", choices: ["Penisola Balcanica", "Penisola Arabica (parte)", "Penisola Iberica"], a: 1, difficulty: "medium", category: "geografia" },
  { q: "Capitale Argentina?", choices: ["Rosario", "Buenos Aires", "Cordoba"], a: 1, difficulty: "medium", category: "geografia" },

  // HARD (20)
  { q: "Punto più basso Terra?", choices: ["Mar Morto (-430m)", "Fossa Marianne", "Death Valley"], a: 0, difficulty: "hard", category: "geografia" },
  { q: "Enclavi Sudafrica?", choices: ["2 (Lesotho, Swaziland)", "3", "1"], a: 0, difficulty: "hard", category: "geografia" },
  { q: "Confine Linea Verde 1949?", choices: ["Confine Libano", "Linea armistizio israelo-araba", "Confine Egitto-Israele"], a: 1, difficulty: "hard", category: "geografia" },
  { q: "Arcipelago più grande?", choices: ["Giappone", "Filippine", "Indonesia"], a: 2, difficulty: "hard", category: "geografia" },
  { q: "Capitale più alta mondo?", choices: ["Quito", "Bogotá", "La Paz"], a: 2, difficulty: "hard", category: "geografia" },
  { q: "Km² Cisgiordania?", choices: ["2.000 km²", "5.860 km²", "10.000 km²"], a: 1, difficulty: "hard", category: "geografia" },
  { q: "Paese con più isole?", choices: ["Svezia (267.570)", "Finlandia", "Canada"], a: 0, difficulty: "hard", category: "geografia" },
  { q: "Deserto più arido?", choices: ["Sahara", "Gobi", "Atacama"], a: 2, difficulty: "hard", category: "geografia" },
  { q: "Area densamente popolata regione?", choices: ["Striscia di Gaza", "Deserto Negev", "Mar Morto"], a: 0, difficulty: "hard", category: "geografia" },
  { q: "Triple point geografico?", choices: ["Punto 3 confini", "Centro geografico", "Polo"], a: 0, difficulty: "hard", category: "geografia" },
  { q: "Km² Striscia Gaza?", choices: ["365 km²", "500 km²", "200 km²"], a: 0, difficulty: "hard", category: "geografia" },
  { q: "Meridiano di Greenwich passa per?", choices: ["Berlino", "Londra", "Parigi"], a: 1, difficulty: "hard", category: "geografia" },
  { q: "Fossa oceanica più profonda?", choices: ["Fossa Tonga", "Fossa Porto Rico", "Fossa Marianne"], a: 2, difficulty: "hard", category: "geografia" },
  { q: "Densità popolazione Gaza?", choices: ["~1.000 ab/km²", "~5.500 ab/km²", "~10.000 ab/km²"], a: 1, difficulty: "hard", category: "geografia" },
  { q: "Stato senza sbocco mare più grande?", choices: ["Kazakhstan", "Chad", "Mongolia"], a: 0, difficulty: "hard", category: "geografia" },
  { q: "Altitudine Gerusalemme?", choices: ["~1.000m", "~750-800m", "~500m"], a: 1, difficulty: "hard", category: "geografia" },
  { q: "Fiume più corto mondo?", choices: ["Roe River (61m)", "Los Patos", "D River"], a: 0, difficulty: "hard", category: "geografia" },
  { q: "Paese con più fusi orari?", choices: ["Russia (11)", "USA (11)", "Francia (12)"], a: 2, difficulty: "hard", category: "geografia" },
  { q: "Latitudine Tel Aviv circa?", choices: ["25°N", "40°N", "32°N"], a: 2, difficulty: "hard", category: "geografia" },
  { q: "Paese più lungo mondo?", choices: ["Chile", "Russia", "Canada"], a: 0, difficulty: "hard", category: "geografia" },
];